baseURL = "https://pgrandinetti.github.io/compilers"
languageCode = "en-us"
title = "Compilers"

DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

math = true

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Nuts and bolts of Programming Languages"
  mainSections = ["post","posts"]
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  #favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  #comments = true
  readingTime = true
  #wordCount = true
  useHLJS = false
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Pietro"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
  github = "pgrandinetti"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
  linkedin = "grandinettipietro"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"

[[menu.main]]
    name = "Contents"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/introduction"
    weight = 2

[[menu.main]]
    name="Code"
    url = "https://github.com/pgrandinetti/compilers"
    weight = 3
